---
- name: Show running Config
  hosts: ios
  connection: ansible.netcommon.network_cli

  tasks:
    - name: sh running config
      cisco.ios.ios_command:
        commands:
          - show run
      register: output

    - name: print output
      ansible.builtin.debug:
        var: output.stdout_lines
