---
- name: Show flash memory
  hosts: ios
  connection: ansible.netcommon.network_cli

  tasks:
    - name: sh flash mem
      cisco.ios.ios_command:
        commands:
          - "show flash:"
      register: output

    - name: print output
      ansible.builtin.debug:
        var: output.stdout_lines
